### ISSUE TITLE
Feature request (return all non-empty cells in a row)

### ISSUE THREAD

**Issue by danieledistanio** [sheetsu/sheetsu-js#4]
Hi Sheetsu,

it will be awesome to have option for cells that are not empty. I tried using "*" but it returns everything, including empty cells.

Something like:
```
{ search: { name: "*is" }, empty: false }
```
so that we could include/exclude empty results at will.

Thank you!!
Daniele

**Comment by erbear** [comment]
This is really easy to implement on your own. Here is an example: https://codepen.io/sheetsu/pen/WEpaeg

**Comment by danieledistanio** [comment]
Thank you Erbert!

In case other non devs like me ;-) are interested, in the pen above you can replace:
```
data.filter(function(item){ return parseInt(item.score) > 70})
```
with
```
data.filter(function(item){ return parseInt(item.score) != ""})
```
Cheers!
Daniele
