### ISSUE TITLE
502 (Bad Gateway) + No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by oneezy** [sheetsu/sheetsu-js#8]
I'm having mixed results w/ the **Sheetsu Web Client**. *(Sometimes it works/ Sometimes it doesn't.)*

Here's a codepen of where I'm experiencing the issue:
https://codepen.io/oneezy/pen/QmWRro?editors=1011

Here's the console error message:

```
(index):1 OPTIONS https://sheetsu.com/apis/v1.0su/5a7570949087/ 502 (Bad Gateway)
(anonymous) @ (index):1
readWithPromise @ (index):1
read @ (index):1
(anonymous) @ pen.js:16
index.html:1 Failed to load https://sheetsu.com/apis/v1.0su/5a7570949087/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access. The response had HTTP status code 502.
```

Here's a screenshot of the console error:
![image](https://user-images.githubusercontent.com/7369575/37206799-be67345c-235f-11e8-874d-565158f9413b.png)

---

Any idea on why this might be happening?

**Comment by jdrzj** [comment]
Hi @oneezy. Our VPS provider had technical issues, sorry for that. Everything should work by now!

**Comment by oneezy** [comment]
thanks mate!

**Comment by nickperdomo** [comment]
@jdrzj I'm seeing the same issue today and yesterday as well.

**Comment by kilianso** [comment]
Same here, it's blocking API calls sporadic showing the CORS error.

**Comment by golightley** [comment]
Same here. Getting a  502 Bad Gateway error.
